# Generated by Django 4.0 on 2024-04-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('phone_number', models.CharField(max_length=16, verbose_name='联系电话')),
                ('address_line1', models.CharField(max_length=100, verbose_name='地址1')),
                ('address_line2', models.CharField(blank=True, max_length=100, verbose_name='地址2')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('state_province', models.CharField(max_length=50, verbose_name='省/州')),
                ('postal_code', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('default', models.BooleanField(default=False, verbose_name='设为默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='accounts.user')),
            ],
        ),
    ]
